USB_VID = 0x239A
USB_PID = 0x80aa
USB_PRODUCT = "Greenpill"
USB_MANUFACTURER = "Stary"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "S25FL064L"
LONGINT_IMPL = MPZ
